eureka:
  client:
    hostname: localhost
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.client.hostname}:${server.port}/eureka/


# Log
logging:
  file: registry.log
  level:
    root: INFO


