spring:
  application:
    name: consumer-service
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411
server:
  port: 1888

eureka:
  server:
    hostname: localhost
    port: 2222
  client:
    serviceUrl:
        defaultZone:  http://${eureka.server.hostname}:${eureka.server.port}/eureka

# Log
logging:
  file: consumer-service.log
  level:
    root: INFO
