spring:
  profiles:
    active: dev
  application:
    name: provider-service
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411
# Jpa
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
# Redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
    timeout: 0

server:
  port: 1999

eureka:
  server:
    hostname: localhost
    port: 2222
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

# Log
logging:
  file: provider-service.log
  level:
    root: INFO
